name: Path To Live Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  actions: read
  checks: write
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash
    working-directory: terraform/account

env:
  TERRAFORM_VERSION: 1.14.1

jobs:
  lint-and-validate:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-production
          role-session-name: opg-shared-network-firewall-github-actions-oidc-main-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Lint Terraform
        id: tf_lint
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        id: tf_validate
        run: |
          terraform init
          terraform validate

  plan-and-apply:
    name: Plan & Apply ${{ matrix.environment }}
    needs: [lint-and-validate]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: "Development"
            workspace_environment: "development"
            role: "oidc-opg-shared-network-firewall-shared-development"

          # - environment: "Production"
          #   workspace_environment: "production"
          #   role: "oidc-opg-shared-network-firewall-shared-production"

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - uses: unfor19/install-aws-cli-action@v1

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-production
          role-session-name: opg-shared-network-firewall-github-actions-oidc-main-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Setup
        run: |
          echo TF_WORKSPACE=${{ matrix.workspace_environment }} >> $GITHUB_ENV
          echo TF_VAR_default_role=${{ matrix.role }} >> $GITHUB_ENV

      - name: Init & Plan
        run: |
          terraform init
          terraform plan --lock-timeout=300s --parallelism=200 --out=${{ env.TF_WORKSPACE }}.plan > ${{ env.TF_WORKSPACE }}.log

      - name: Output Plan
        run: |
          cat ${{ env.TF_WORKSPACE }}.log
          echo ''
          echo '----------------------Concise Plan---------------------------'
          cat ${{ env.TF_WORKSPACE }}.log | grep '\.' | grep '#' || true

      - name: Apply ${{ matrix.environment }}
        run:  terraform apply -parallelism=200 -lock-timeout=300s ${{ env.TF_WORKSPACE }}.plan
