name: PR Workflow Build

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  actions: read
  checks: write
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash
    working-directory: terraform/account

env:
  TERRAFORM_VERSION: 1.14.1

jobs:
  lint-and-validate:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-development
          role-session-name: opg-shared-network-firewall-github-actions-oidc-pr-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Lint Terraform
        id: tf_lint
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        id: tf_validate
        run: |
          terraform init
          terraform validate

  plan-against-development:
    name: Plan Development
    runs-on: ubuntu-latest
    needs: [lint-and-validate]
    env:
      TF_VAR_default_role: "oidc-opg-shared-network-firewall-shared-development"
      TF_WORKSPACE: "development"
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - uses: unfor19/install-aws-cli-action@v1

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-development
          role-session-name: opg-shared-network-firewall-github-actions-oidc-pr-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Init & Plan
        run: |
          terraform init
          terraform plan --lock-timeout=300s --parallelism=200
