name: PR Workflow Build

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  actions: read
  checks: write
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

defaults:
  run:
    shell: bash
    working-directory: terraform/account

env:
  TFLINT_VERSION: 0.50.1

jobs:
  lint-and-validate:
    name: 'Validate Infrastructure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse terraform version
        id: tf_version_setup
        run: |
          if [ -f ./versions.tf ]; then
            terraform_version=$(cat ./versions.tf | sed -r -n 's/.*required_version.*"(.*)"$/\1/p' <&0)
            echo "- Terraform version: [${terraform_version}]" >> $GITHUB_STEP_SUMMARY
            echo "TERRAFORM_VERSION=${terraform_version}" >> $GITHUB_OUTPUT
          fi

      - name: "Terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"
        run: echo "terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6 # v5
        name: Setup TFLint
        with:
          tflint_version: v${{ env.TFLINT_VERSION }}

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-development
          role-session-name: opg-shared-network-firewall-github-actions-oidc-pr-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Format Check Terraform
        id: tf_fmt
        run: terraform fmt -check -recursive

      - name: Validate Terraform
        id: tf_validate
        run: |
          terraform init
          terraform validate

      - name: Lint Terraform
        id: tf_lint
        run: tflint --recursive

  plan-against-development:
    name: Plan Development
    runs-on: ubuntu-latest
    needs: [lint-and-validate]
    env:
      TF_VAR_default_role: "oidc-opg-shared-network-firewall-shared-development"
      TF_WORKSPACE: "development"
    steps:
      - uses: actions/checkout@v2

      - name: Parse terraform version
        id: tf_version_setup
        run: |
          if [ -f ./versions.tf ]; then
            terraform_version=$(cat ./versions.tf | sed -r -n 's/.*required_version.*"(.*)"$/\1/p' <&0)
            echo "- Terraform version: [${terraform_version}]" >> $GITHUB_STEP_SUMMARY
            echo "TERRAFORM_VERSION=${terraform_version}" >> $GITHUB_OUTPUT
          fi

      - name: "Terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"
        run: echo "terraform version [${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}]"

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ steps.tf_version_setup.outputs.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - uses: unfor19/install-aws-cli-action@v1

      - name: Configure OIDC AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::631181914621:role/oidc-opg-shared-network-firewall-development
          role-session-name: opg-shared-network-firewall-github-actions-oidc-pr-build
          role-duration-seconds: 900
          aws-region: eu-west-1

      - name: Init & Plan
        run: |
          terraform init
          terraform plan --lock-timeout=300s --parallelism=200
